### PR TITLE
Dev branch

### PR DESCRIPTION
**Pull request by arkohaddoebenezer**
Following AmaliTech Git Approach we are required to have a development branch. this is the base branch which we will use for our feature branches henceforth instead of branching from main/master.

Screenshot (333)

### CODE REVIEW

**Comment by amponsemmichael** [comment]
Great, then let's follow the approach.

**Review by amponsemmichael — APPROVED** [review]
Refactoring acknowledged.

**Comment by hale-Dennis** [comment]
Great

**Review by hale-Dennis — APPROVED** [review]

**Review by Abynahisblue — APPROVED** [review]
good one
Eben: I think we are good to go, we can merge now

**Pull request merged**
