### PR TITLE
chore: ci/cd integration

### PR DESCRIPTION
**Pull request by arkohaddoebenezer**

### CODE REVIEW

**Comment by sayv-xo** [comment]
all checks are failing.

**Comment by sayv-xo** [comment]
ltgm

**Comment by arkohaddoebenezer** [comment]
> all checks are failing.

fixed now

**Comment by arkohaddoebenezer** [comment]
> ltgm

Meaning??

**Review by sayv-xo — APPROVED** [review]
all good.

**Review by Abynahisblue — COMMENTED** [review]
looks good

**Pull request merged**
