### PR TITLE
Feature interface

### PR DESCRIPTION
**Pull request by hale-Dennis**
Created the general interface for the text processing tool and added controllers(not fully implemented) for the Menu items.

### CODE REVIEW

**Review by amponsemmichael — APPROVED** [review]
Good job done.

**Comment by arkohaddoebenezer** [comment]
Great work

**Review by Abynahisblue — APPROVED** [review]

**Comment by arkohaddoebenezer** [comment]
Pls there is conflict kindly resolve

**Comment by hale-Dennis** [comment]
> Pls there is conflict kindly resolve
conflict resolved

**Review by arkohaddoebenezer — APPROVED** [review]

**Review by sayv-xo — APPROVED** [review]

**Pull request merged**
